version: '3.8'
services:
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      observabilidad:
        ipv4_address: 192.168.1.149

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /home/server/git/Cyberseguridad/sbom/:/var/log/auditoria:ro
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki
    networks:
      observabilidad:
        ipv4_address: 192.168.1.150

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      observabilidad:
        ipv4_address: 192.168.1.151

volumes:
  grafana_data:

networks:
  observabilidad:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
