auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 30s
  wal:
    enabled: true
    dir: /loki/wal   # 👈 cambiado

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index   # 👈 cambiado
    cache_location: /loki/cache           # 👈 cambiado
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks               # 👈 cambiado

compactor:
  working_directory: /loki/compactor      # 👈 cambiado
  shared_store: filesystem

limits_config:
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6
  max_cache_freshness_per_query: 10m

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 24h
