scrape_configs:
  - job_name: auditoria
    static_configs:
      - targets:
          - localhost
        labels:
          job: auditoria
          __path__: /var/log/auditoria/sbom/*.ndjson
    pipeline_stages:
      - json
