server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push   # si Grafana y Loki están en la misma red de Docker
  # - url: http://192.168.1.149:3101/loki/api/v1/push   # si quieres apuntar al host expuesto

scrape_configs:
  - job_name: auditoria
    static_configs:
      - targets:
          - localhost
        labels:
          job: auditoria
          __path__: /var/log/auditoria/sbom/*.ndjson
    pipeline_stages:
      - json
