version: '3.8'
services:
  backend:
    build: .
    container_name: fs-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_NAME=fs_backend
      - DB_USER=fs_user
      - DB_PASS=MiClaveSegura123!
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:8.0
    container_name: fs-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: fs_backend
      MYSQL_USER: fs_user
      MYSQL_PASSWORD: MiClaveSegura123!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

