name: Test Loki Cloud

on:
  workflow_dispatch:   # lo puedes lanzar manualmente desde la pestaña Actions

jobs:
  send-log:
    runs-on: ubuntu-latest
    steps:
      - name: Generar log de prueba
        run: echo '{"msg":"Hola Erik, este es un log de prueba desde GitHub Actions"}' > output.ndjson

      - name: Enviar log a Grafana Cloud Loki
        run: |
          while read -r line; do
            ts=$(date +%s%N)
            payload=$(jq -c -n --arg log "$line" \
              '{streams: [{stream: {job:"auditoria", tool:"test", branch:"'${GITHUB_REF##*/}'"}, values:[[env.ts, $log]]}]}')
            curl -u "${{ secrets.GRAFANA_USER }}:${{ secrets.GRAFANA_API_KEY }}" \
              -H "Content-Type: application/json" \
              -X POST https://logs-prod-012.grafana.net/loki/api/v1/push \
              --data-raw "$payload"
          done < output.ndjson
