name: Deploy informes de auditoría

on:
  workflow_dispatch:   # lo lanzas manualmente
  workflow_run:        # o lo encadenas al anterior
    workflows: ["Auditoría de código"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar artefactos
        uses: actions/download-artifact@v4
        with:
          name: auditoria-json

      - name: Configurar clave SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.168.1.149 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Subir informes al servidor
        run: |
          scp eslint_report.json server@192.168.1.149:/var/log/auditoria/eslint_report.json
          scp semgrep_report.json server@192.168.1.149:/var/log/auditoria/semgrep_report.json
          scp gitleaks_report.json server@192.168.1.149:/var/log/auditoria/gitleaks_report.json
