name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          projectKey: Cyberseguridad
          projectName: Cyberseguridad
          args: >
            -Dsonar.host.url=http://192.168.1.149:9000
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
